name: "Voyanti UXR Addon Gen"
description: "Voyanti UXR Addon Gen"
version: "1.0.4"
slug: "uxr_gen"
url: "https://github.com/heinrich321/voyanti-uxr-charger/gen_cluster"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

uart: true
usb: true
startup: system

options:
  mqtt_host: "10.0.0.132"
  mqtt_port: 1883
  mqtt_user: "mqtt-users"
  mqtt_password: "mqtt-users"
  mqtt_ha_discovery: true
  mqtt_ha_discovery_topic: "homeassistant"
  mqtt_base_topic: "uxr"
  port: "/dev/ttyACM1"
  scan_interval: 10
  read_delay: 0.02
  default_current_limit: 30
  default_voltage: 775
  debug_output: 0
  modules:
    - SERIAL_NR: "1"
      HA_PREFIX: GEN
      CANBUS_ID: 0
      GROUP_ID: 5
    - SERIAL_NR: "2"
      HA_PREFIX: GEN
      CANBUS_ID: 1
      GROUP_ID: 5
    - SERIAL_NR: "3"
      HA_PREFIX: GEN
      CANBUS_ID: 2
      GROUP_ID: 5
    - SERIAL_NR: "4"
      HA_PREFIX: GEN
      CANBUS_ID: 3
      GROUP_ID: 5
schema:
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str
  mqtt_password: str
  mqtt_ha_discovery: bool
  mqtt_ha_discovery_topic: str
  mqtt_base_topic: str
  port: str
  scan_interval: int
  read_delay: int
  debug_output: int
  default_current_limit: int
  default_voltage: int
  modules:
    - SERIAL_NR: str
      HA_PREFIX: str
      CANBUS_ID: int
      GROUP_ID: int